export class PatientDto {
    // PatientId: number;
    ChartNumber: string;
    Ssn: string;
    DateOfBirth: any;
    ageValue?: any;
    SalutationId: number;
    MaritalStatusId: number;
    Sex: boolean;
    ReligionId: number;
    RaceId: number;
    EthnicityId: number;
    Language1Id: number;
    Language2Id: number;
    Language3Id: number;
    RequiresInterpreter: boolean;
    FirstName: string;
    MiddleName: string;
    LastName: string;
    PrimaryAddressLine1: string;
    PrimaryAddressLine2: string;
    PrimaryCity: string;
    PrimaryStateCode: string;
    PrimaryZipCode: string;
    PrimaryZipPlus4: string;
    SecondaryAddressLine1: string;
    SecondaryAddressLine2: string;
    SecondaryCity: string;
    SecondaryStateCode: string;
    SecondaryZipCode: string;
    SecondaryZipPlus4: string;
    HasInternationalAddress: boolean;
    WorkPhone: string;
    WorkPhoneExt: string;
    HomePhone: string;
    MobilePhone: string;
    AltPhone: string;
    Fax: string;
    PreferredContactNo: number;
    PhotoImage: string;
    Email1: string;
    Email2: string;
    GeneralNote: string;
    Occupation: string;
    HipaaViaMail: boolean;
    HipaaViaVoice: boolean;
    HipaaViaNotice: boolean;
    HipaaViaMessage: boolean;
    HipaaAllowSms: boolean;
    HipaaAllowEmail: boolean;
    PriceLevel: string;
    PatientStatus: any;
    ReferralSourceId: number;
    DateCreated: string;
    CreatedByUserId: number;
    DateLastUpdated: string;
    LastUpdatedByUserId: number;
    SignatureOnFile: boolean;
    AssignedProvider: number;
    SofDate: string;
    MedicalChartNumber: string;
    DefaultFacility: number;
    DefaultPhysician: number;
    UserId: number;
    ApplicationUserId: number;
    HippaAllowPhoneCall: boolean;
    HippaAllowPatientPortal: boolean;
    PatientPortalMakeClinicalSummaryAvailableToPatient: boolean;
    PatientPortalMakeLabResultsAvailableToPatient: boolean;
    PatientPortalMakeProblemListAvailableToPatient: boolean;
    PatientPortalMakeMedicationListAvailableToPatient: boolean;
    PatientPortalMakeAllergyInfoAvailableToPatient: boolean;
    PatientPortalMakeRadiologyReportsInfoAvailableToPatient: boolean;
    PatientPortalMakeReferralLettersInfoAvailableToPatient: boolean;
    ReferringPhysicianId: number;
    ReferringOrganizationId: number;
    ReferralDetails: string;
    SummaryDocument: string;
    AmountCurrentBalanceDue: number;
    AmountCurrentBalanceDueCurrency: string;
    DateCurrentBalanceDue: string;
    OnPaymentArrangement: boolean;
    UniqueNumber: string;
    IsLivingWill: boolean;
    AdvancedDirectivesId: boolean;
    Note: string;
    FlagSelfPayPatient: boolean;
    FlagDoNotSendPatientStatement: boolean;
    Comments: string;
    InsuranceCategoryId: number;
    AcceptAssignment: boolean;
    RcopiaPatientId: string;
    RcopiaXml: string;
    ResponsibleParty: string;
    // Appointments: Array;
    // BillTransactions: Array;
    // BillersNotes: Array;
    // CollectionTasks: Array;
    // MrAssessmentDiagnosis: Array;
    // MrChiefComplaints: Array;
    // MrPatientEncounterCptDiagnosisAssociations: Array;
    // MrPatientEncounters: Array;
    // MrPlanProcedures: Array;
    // MrProblemLists: Array;
    // MrVitals: Array;
    // PatientAccountActivities: Array;
    // PatientInsuranceProviders: Array;
    // Superbills: Array;
    // Visits: Array;
    constructor() {
        // this.PatientStatus = '1'
    }
}
