import { Menu } from './menu.model';
export const verticalMenuItems = [
      /*WorkSpace*/
    new Menu(1, 'WorkSpace', '/pages/workspace', null, 'Workspace.svg',null, false, 0,'WorkspaceActive.svg'),
    new Menu(2,"Patient Management",'/pages/workspace/patientmanagement', null, 'Patient.svg',null, false, 1),
    new Menu(4, 'Check Availability', '/pages/workspace/chkavl', null, 'Check.svg', null, false, 1),
    new Menu(5, 'Forms', '/pages/workspace/forms', null, 'Forms.svg', null, false, 1),
    new Menu(6, 'User Schedule', '/pages/workspace/userschedule', null, 'Schedule.svg', null, false, 1),
    new Menu(7, 'View All Appointments', '/pages/workspace/v-all-appointments', null, 'AllAppointment.svg', null, false, 1),
    // new Menu(8, 'View Charts', '/pages/workspace/v-charts', null, 'file-text-o', null, false, 1),
    new Menu(8, 'View Charts', '/pages/chart', null, 'PatientCharts.svg', null, false, 1),
    new Menu(9, 'Referring Physician', '/pages/workspace/referringphysician', null, 'Referring.svg',null, false, 1),
// new Menu(10, 'Availability Exception', '/pages/workspace/exception', null, 'list-alt', null, false, 1),
    /*Scheduling*/
    new Menu(12, 'Scheduling', '/pages/scheduling', null, 'UserSchedules.svg',null, false, 0,'ScheduleActive.svg'),
    new Menu(13, 'Patient Management', '/pages/scheduling/patientmanagement', null, 'Patient.svg',null, false, 12), 
    // new Menu(13, 'Find Patient', '/pages/scheduling/findpatient', null, 'wheelchair', null, false, 12),
    // new Menu(14, 'Register Patient', '/pages/scheduling/registerpatient', null, 'Patient.svg', null, false, 12),
    new Menu(15, 'Check Availability', '/pages/scheduling/chkavl', null, 'Check.svg',  null, false, 12),
    new Menu(16, 'Forms', '/pages/scheduling/forms', null, 'Forms.svg', null, false, 12),
    new Menu(17, 'User Schedule', '/pages/scheduling/userschedule', null, 'Schedule.svg',null, false, 12),
    new Menu(18, 'View All Appointments', '/pages/scheduling/v-all-appointments', null, 'AllAppointment.svg', null, false, 12),
    new Menu(19, 'View Charts', '/pages/scheduling/v-charts', null, 'PatientCharts.svg', null, false, 12),
    new Menu(20, 'Referring Physician', '/pages/scheduling/referringphysician', null, 'Referring.svg',null, false, 12),
    // new Menu(21, 'Register Patients' , '/pages/scheduling/register-patient', null, 'file-text', null, false, 12),
    /*Charts*/
    new Menu(24, 'Charts', '/pages/chart', null, 'chartsHome.svg', null, false, 0,'chartsHomeActive.svg'),
    // new Menu(25, 'Patient Details', null, null, 'file-text-o', null, true, 24),  
    // // new Menu(26, 'Find Patient', '/pages/chart/findpatient', null, 'search', null, false, 24),
    // new Menu(27, 'Edit Patient Details', '/pages/chart/edt-pt-details', null, 'pencil', null, false, 24),
    new Menu(28, 'Progress Note', '/pages/chart/progressnote', null, 'ProgressNote.svg',null, false, 24),
    new Menu(29, 'Prescribe', '/prescribe/1', null, 'Prescribe.svg', '_blank', false, 24),
    // new Menu(30, 'Add Details', null, null, 'plus-square', null, true, 24),
    new Menu(31, 'Add Problem', '/pages/chart/add-problems', null, 'AddProblem.svg',null, false, 24),
    new Menu(32, 'Add PMH', '/pages/chart/add-pmh', null, 'AddPMH.svg', null, false, 24),
    new Menu(33, 'Add Allergy', '/pages/chart/add-allergy', null, 'AddAllergy.svg', null, false, 24),
    new Menu(34, 'Immunization Schedule', '/pages/chart/immunz-sche', null, 'ImmunizationSchedule.svg', null, false, 24),
    new Menu(35, 'Add Vitals', '/pages/chart/add-vitals', null, 'AddVitals.svg',null, false, 24),
    new Menu(36, 'Add Investigation', '/pages/chart/add-invest', null, 'AddInvestigation.svg', null, false, 24),
    new Menu(37, 'Graphs', '/pages/chart/graphs', null, 'Graph.svg', null, false, 24),
    // new Menu(38, 'Share', null, null, 'share-alt', null, true, 24),
    new Menu(39, 'Documents', '/pages/chart/documents', null, 'Documents.svg', null, false, 24),
    new Menu(40, 'Letters', '/pages/chart/letters', null, 'Letters.svg', null, false, 24),
    new Menu(41, 'Messages', '/pages/chart/msg', null, 'Messages.svg',null, false, 24),
    new Menu(42, 'Sketch Pad', '/pages/chart/sktch-pad', null, 'SketchPad.svg', null, false, 24),
    new Menu(43, 'All Charts Print', '/pages/chart/all-chart-pt', null, 'AllChartsPatients.svg', null, false, 24),
    /*Billing*/
    new Menu (45, 'Billing', '/pages/billing/viewbills', null, 'Billing.svg', null, false, 0,'BillingActive.svg'),
    new Menu (46, 'View Bills', '/pages/billing/viewbills', null, 'ViewBills.svg',null, false, 45),
    new Menu (47, 'Post Charges', '/pages/billing/postcharges', null, 'PostCharges.svg',null, false, 45),
    new Menu (48, 'Claims', '/pages/billing/claims', null, 'Claims.svg', null, false, 45),
    new Menu (49, 'Payments', '/pages/billing/payments', null, 'Payments.svg', null, false, 45),
    new Menu (50, 'Patient Accounts', '/pages/billing/patientaccount', null, 'PatientAccounts.svg',null, false, 45),
    new Menu (51, 'Account Receivable', '/pages/billing/accountreceivable', null, 'AccountReceivable.svg', null, false, 45),
    new Menu (52, 'Billing Setup', '/pages/billing/billingsetup', null, 'BillingSetup.svg', null, false, 45),
    new Menu(53, 'Billing Portal', '/pages/billing/billingportal', null, 'BillingPortal.svg',null, false, 45),
    /*Orders*/
    new Menu(60, 'Orders', "/pages/orders", null, 'Orders.svg', null, false, 0,'OrdersActive.svg'),
    // new Menu(61, 'Find Patients', '/pages/orders/findpatients', null, 'FindPatient.svg', null, false, 60),
    new Menu(62, 'Home', '/pages/orders/home', null, 'home.svg', null, false, 60),
    new Menu(63, 'New Order', '/pages/orders/neworder', null, 'NewFolder.svg', null, false, 60),
    new Menu(64, 'Search', '/pages/orders/search', null, 'Search.svg', null, false, 60),
    new Menu(65, 'Inbox', '/pages/orders/inbox', null, 'Inbox.svg', null, false, 60),
    new Menu(66, 'Admin', '/pages/orders/admin', null, 'Admin.svg',null, true, 60),
    // new Menu(661, 'Test Code Preference', '/pages/orders/testcodepreference', null, 'PatientManagement.svg','PatientActive.svg', null, false, 60),
    // new Menu(662, 'ICD Code Preference', '/pages/orders/icdcodepreference', null, 'PatientManagement.svg', 'PatientActive.svg',null, false, 60)
,    new Menu(67, 'Mail Portal', '/pages/orders/mainportal', null, 'MainPortal.svg', null, false, 60),
    new Menu(68, 'Show Results', '/pages/orders/showresults', null, 'Showresult.svg', null, false, 60),

    /*Practice*/
    new Menu(71, 'Practice',null, null, 'Practice.svg', null, true, 71),
    new Menu(72, 'Practive-Mngt', null, null, 'users', null, true, 71),
    new Menu(73, 'Facility', '/pages/practice/facility', null, 'PatientManagement.svg', null, false, 72),
    new Menu(74, 'Practice', '/pages/practice/pm-practice', null, 'PatientManagement.svg', null, false, 72),
    new Menu(75, 'Speciality', '/pages/practice/pm-speciality', null, 'PatientManagement.svg', null, false, 72),
    new Menu(76, 'Qualification', '/pages/practice/pm-qual', null, 'PatientManagement.svg', null, false, 72),
    new Menu(77, 'Employee Role', '/pages/practice/pm-emp-role', null, 'PatientManagement.svg', null, false, 72),
    new Menu(78, 'LookUp Table', '/pages/practice/pm-lup-tb', null, 'PatientManagement.svg', null, false, 72),
    new Menu(79, 'Eligibility Verification', '/pages/practice/pm-el-verf', null, 'PatientManagement.svg', null, false, 72),
    new Menu(80, 'Employee Maintenance', '/pages/practice/pm-employee-maintenance', null, 'PatientManagement.svg', null, false, 72),
    new Menu(81, 'Clinical Decition Support', '/pages/practice/pm-cds', null, 'PatientManagement.svg', null, false, 72),

    // new Menu(82, 'Reports', "pages/reports", null, 'Reports.svg', null, false, 0,'ReportsActive.svg'),
    // new Menu(83, 'Patients List', '/pages/practice/rt-pt-list', null, 'PatientManagement.svg', null, false, 82),
    // new Menu(84, 'Audit Report', '/pages/practice/rt-audit-report', null, 'PatientManagement.svg', null, false, 82),
    // new Menu(85, 'Patient Remainder', '/pages/practice/rt-pt-remainder', null, 'PatientManagement.svg', null, false, 82),
    // new Menu(86, 'Stage1 MU Measures', '/pages/practice/rt-mum', null, 'PatientManagement.svg', null, false, 82),
    // new Menu(87, 'Clinical Qty Measure', '/pages/practice/rt-cqm', null, 'PatientManagement.svg', null, false, 82),

    new Menu(88, 'Health Info Exg', null, null, 'PatientManagement.svg', null, true, 71),
    new Menu(89, 'Ept/Dpt EHI', '/pages/practice/hie-ed-ehi', null, null, null, false, 88),
    new Menu(90, 'Generate SHA256', '/pages/practice/hie-audit-gshah', null, null, null, false, 88),
    new Menu(91, 'General Enc Test', '/pages/practice/hie-getst', null, null, null, false, 88),
    new Menu(92, 'Public Health Surv', '/pages/practice/hie-phs', null, null, null, false, 88),
    new Menu(93, 'Electronic Exg Cpt', '/pages/practice/hie-eec', null, null, null, false, 88),
    new Menu(94, 'Exg Clinical Info', '/pages/practice/hie-exc-cli-info', null, null, null, false, 88),
    new Menu(95, 'Imm.Reg Submission', '/pages/practice/hie-irs', null, null, null, false, 88),
    new Menu(96, 'Sync DrFirst Data', '/pages/practice/hie-sdd', null, null, null, false, 88),


    new Menu(97, 'Administration', null, null, 'PatientManagement.svg', null, true, 71),
    new Menu(98, 'Modality', '/pages/practice/admin-modality', null, 'PatientManagement.svg', null, false, 97),
    new Menu(99, 'Department', '/pages/practice/admin-dept', null, 'PatientManagement.svg', null, false, 97),
    new Menu(100, 'Place Of Service', '/pages/practice/admin-pos', null, 'PatientManagement.svg', null, false, 97),
    new Menu(101, 'Calendar Event', '/pages/practice/admin-cal-evt', null, 'PatientManagement.svg', null, false, 97),
    new Menu(102, 'Reffering Physician', '/pages/practice/admin-reff-phy', null, 'PatientManagement.svg', null, false, 97),
    new Menu(103, 'Related Organization', '/pages/practice/admin-rlorg', null, 'PatientManagement.svg', null, false, 97),
    new Menu(104, 'Unit of Measure', '/pages/practice/admin-uom', null, 'PatientManagement.svg', null, false, 97),
    new Menu(105, 'CPT4 Codes', '/pages/practice/admin-cptcode', null, 'PatientManagement.svg', null, false, 97),
    new Menu(106, 'Laboratories', '/pages/practice/admin-lab', null, 'PatientManagement.svg', null, false, 97),
    new Menu(107, 'Lab Investigations', '/pages/practice/admin-lab-invest', null, 'PatientManagement.svg', null, false, 97),
    new Menu(108, 'Investigations', '/pages/practice/admin-invest', null, 'PatientManagement.svg', null, false, 97),
    new Menu(109, 'Merge Patient', '/pages/practice/admin-mg-patient', null, 'PatientManagement.svg', null, false, 97),

    new Menu(110, 'Template', null, null, null, null, true, 88),
    new Menu(111, 'Section Builder', '/pages/practice/templat-sb', null, 'PatientManagement.svg', null, false, 110),
    new Menu(112, 'Smart Text Lookups', '/pages/practice/template-stl', null, 'PatientManagement.svg', null, false, 110),
    new Menu(113, 'Smart Note Template', '/pages/practice/template-snt', null, 'PatientManagement.svg', null, false, 110),
    new Menu(114, 'Template Group', '/pages/practice/template-tg', null, 'PatientManagement.svg', null, false, 110),
    new Menu(115, 'Patient Edu Resource', '/pages/practice/template-per', null, 'PatientManagement.svg', null, false, 110),
    new Menu(116, 'Letter Template', '/pages/practice/template-lt', null, 'PatientManagement.svg', null, false, 110),
    new Menu(117, 'Encounter Sum Temp', '/pages/practice/template-est', null, 'PatientManagement.svg', null, false, 110),

    /*Reports*/
    new Menu(121, 'Reports', "pages/reports", null, 'Reports.svg', null, false, 0,'ReportsActive.svg'),
    // new Menu(123, 'Appointments', '/pages/reports/appointments', null, 'Appointment.svg', null, false, 121),
    // new Menu(124, 'Billing', '/pages/reports/billing', null, 'BillingReports.svg', null, false, 121),
    // new Menu(125, 'Patients', '/pages/reports/patients', null, 'ReportPatient.svg', null, false, 121),
    // new Menu(126, 'Practice', '/pages/reports/practice', null, 'Practice.svg',null, false, 121),
    // new Menu(127, 'Users', '/pages/reports/userst', null, 'User.svg',null, false, 121),
     /*Scanning*/
    new Menu(131, 'Scanning', '/pages/scanning', null, 'Scan.svg', null, false, 0,'ScanActive.svg'),
    new Menu(132, 'Home', '/pages/scanning/home', null, 'FindPatient.svg', null, false, 131),
    new Menu(133, 'Documents', '/pages/scanning/documents', null, 'Documents.svg', null, false, 131),

    /*Inventory*/
    new Menu(136, 'Inventory', '/pages/inventory/tracking', null,  'Inventory.svg', null, false, 0,'InventoryActive.svg'),
    new Menu(137, 'Tracking', '/pages/inventory/tracking', null, 'Tracking.svg', null, false, 136),
    new Menu(138, 'Items', '/pages/inventory/items', null, 'Items.svg',null, false, 136),
    new Menu(139, 'Batches', '/pages/inventory/batches', null, 'Batches.svg',null, false, 136),
    new Menu(140, 'Orders', '/pages/inventory/orderMaster', null, 'InventoryOrders.svg',null, false, 136),
    new Menu(141, 'Shipping', '/pages/inventory/shipping', null, 'Shipping.svg',null, false, 136),
    new Menu(142, 'Categories', '/pages/inventory/categories', null, 'Categories.svg',null, false, 136),
    new Menu(143, 'Upload', '/pages/inventory/uploads', null, 'Upload.svg',null, false, 136),

    /* Profile */
    // new Menu(144, 'Profile', '/pages/profile', null, 'Inventory.svg', null, false, 0,'InventoryActive.svg'),

    /*Help*/
    // new Menu(145, 'Help', '/pages/help/videos', null, 'Help.svg',null, false, 0, 'HelpActive.svg'),
    // new Menu(146, 'Videos', '/pages/help/videos', null, 'PatientManagement.svg',null, false, 145),
    // new Menu(147, 'User Manual', '/pages/help/um', null, 'PatientManagement.svg',null, false, 145),
    // new Menu(148, 'Whats New', '/pages/help/whatsnew', null, 'PatientManagement.svg', null, false, 145),
    // new Menu(149, 'About', '/pages/help/about', null, 'PatientManagement.svg',null, false, 145),
    new Menu(145, 'Help', '/pages/help/videos', null,  'Help.svg', null, false, 0,'HelpActive.svg'),
    new Menu(146, 'Videos', '/pages/help/videos', null, 'Tracking.svg', null, false, 145),
    new Menu(147, 'User Manual', '/pages/help/um', null, 'Items.svg',null, false, 145),
    new Menu(148, 'Whats New', '/pages/help/whatsnew', null, 'Batches.svg',null, false, 145),
    new Menu(149, 'About', '/pages/help/about', null, 'InventoryOrders.svg',null, false, 145),
  
      /*Logout*/
      // new Menu(151, 'Log Out', null, null, 'calendar', null, false, 0),

    /*new Menu (2, 'Membership', '/pages/membership', null, 'users', null, false, 0),
    new Menu (3, 'UI Features', null, null, 'l  aptop', null, true, 0),
    new Menu (4, 'Buttons', '/pages/ui/buttons', null, 'keyboard-o', null, false, 3),
    new Menu (5, 'Cards', '/pages/ui/cards', null, 'address-card-o', null, false, 3),
    new Menu (6, 'Components', '/pages/ui/components', null, 'creative-commons', null, false, 3),
    new Menu (7, 'Icons', '/pages/ui/icons', null, 'font-awesome', null, false, 3),
    new Menu (8, 'List Group', '/pages/ui/list-group', null, 'th-list', null, false, 3),
    new Menu (9, 'Media Objects', '/pages/ui/media-objects', null, 'object-group', null, false, 3),
    new Menu (10, 'Tabs & Accordions', '/pages/ui/tabs-accordions', null, 'server', null, false, 3),
    new Menu (11, 'Typography', '/pages/ui/typography', null, 'font', null, false, 3),
    new Menu (15, 'Dynamic Menu', '/pages/dynamic-menu', null, 'list-ul', null, false, 0),
    new Menu (16, 'Mailbox', '/pages/mailbox', null, 'envelope-o', null, false, 0),
    new Menu (20, 'Form Elements', null, null, 'pencil-square-o', null, true, 0),
    new Menu (21, 'Form Controls', '/pages/form-elements/controls', null, 'check-square-o', null, false, 20),
    new Menu (22, 'Form Layouts', '/pages/form-elements/layouts', null, 'th-large', null, false, 20),
    new Menu (23, 'Form Validations', '/pages/form-elements/validations', null, 'exclamation-triangle', null, false, 20),
    new Menu (24, 'Form Wizard', '/pages/form-elements/wizard', null, 'magic', null, false, 20),
    new Menu (25, 'Editor', '/pages/form-elements/editor', null, 'pencil', null, false, 20),
    new Menu (26, 'Tables', null, null, 'table', null, true, 0),
    new Menu (27, 'Basic Tables', '/pages/tables/basic-tables', null, 'th', null, false, 26),
    new Menu (28, 'Dynamic Tables', null, null, 'th-large', null, true, 26),
    new Menu (29, 'Smart DataTable', '/pages/tables/dynamic-tables/smart', null, 'caret-right', null, false, 28),
    new Menu (30, 'NGX DataTable', '/pages/tables/dynamic-tables/ngx', null, 'caret-right', null, false, 28),
    new Menu (31, 'Tools', null, null, 'wrench', null, true, 0),
    new Menu (32, 'Drag & Drop', '/pages/tools/drag-drop', null, 'hand-paper-o', null, false, 31),
    new Menu (33, 'Resizable', '/pages/tools/resizable', null, 'expand', null, false, 31),
    new Menu (34, 'Toaster', '/pages/tools/toaster', null, 'bell-o', null, false, 31),
    new Menu (40, 'Pages', null, null, 'file-text-o', null, true, 0),
    new Menu (43, 'Login', '/login', null, 'sign-in', null, false, 40),
    new Menu (44, 'Register', '/register', null, 'registered', null, false, 40),
    new Menu (45, 'Blank', '/pages/blank', null, 'file-o', null, false, 40),
    new Menu (46, 'Error', '/pagenotfound', null, 'exclamation-circle', null, false, 40),
    new Menu (50, 'Calendar', '/pages/calendar', null, 'calendar', null, false, 0),
    new Menu (66, 'Maps', null, null, 'globe', null, true, 0),
    new Menu (67, 'Google Maps', '/pages/maps/googlemaps', null, 'map-marker', null, false, 66),
    new Menu (68, 'Leaflet Maps', '/pages/maps/leafletmaps', null, 'map-o', null, false, 66),
    new Menu (70, 'Charts', null, null, 'area-chart', null, true, 0),
    new Menu (71, 'Bar Charts', '/pages/charts/bar', null, 'bar-chart', null, false, 70),
    new Menu (72, 'Pie Charts', '/pages/charts/pie', null, 'pie-chart', null, false, 70),
    new Menu (73, 'Line Charts', '/pages/charts/line', null, 'line-chart', null, false, 70),
    new Menu (74, 'Bubble Charts', '/pages/charts/bubble', null, 'comment-o', null, false, 70),
    new Menu (140, 'Level 1', null, null, 'folder-open-o', null, true, 0),
    new Menu (141, 'Level 2', null, null, 'folder-open-o', null, true, 140),
    new Menu (142, 'Level 3', null, null, 'folder-open-o', null, true, 141),
    new Menu (143, 'Level 4', null, null, 'folder-open-o', null, true, 142),
    new Menu (144, 'Level 5', null, null, 'folder-o', null, false, 143),*/
    // new Menu (200, 'External Link', null, 'http://themeseason.com', 'Inventory.svg', '_blank', false, 0,'InventoryActive.svg')
]

export const horizontalMenuItems = [
    /*WorkSpace*/
    new Menu(1, 'WorkSpace', '/pages/workspace/1', null, 'Workspace.svg', null, true, 0),
    new Menu(2, 'Patient Management', '/pages/workspace/patientmanagement', null, 'address-book-o', null, false, 1),
    // new Menu(3, 'Register Patient', '/pages/workspace/registerpatient', null, 'file-text', null, false, 1),
    new Menu(4, 'Check Availability', '/pages/workspace/chkavl', null, 'file-text-o', null, false, 1),
    new Menu(5, 'Forms', '/pages/workspace/forms', null, 'file', null, false, 1),
    new Menu(6, 'User Schedule', '/pages/workspace/userschedule', null, 'clock-o', null, false, 1),
    new Menu(7, 'View All Appointments', '/pages/workspace/v-all-appointments', null, 'stethoscope', null, false, 1),
    // new Menu(8, 'View Charts', '/pages/workspace/v-charts', null, 'file-text-o', null, false, 1),
    new Menu(8, 'View Charts', '/pages/chart', null, 'file-text-o', null, false, 1),
    new Menu(9, 'Referring Physician', '/pages/workspace/referringphysician', null, 'user-md', null, false, 1),
    // new Menu(10, 'Availability Exception', '/pages/workspace/exception', null, 'list-alt', null, false, 1),

    /*Scheduling*/
    new Menu(12, 'Scheduling', '/pages/scheduling', null, 'Schedule.svg', null, true, 0),
    new Menu(13, 'Patient Management', '/pages/scheduling/patientmanagement', null, 'address-book-o', null, false, 12),
    // new Menu(13, 'Find Patient', '/pages/scheduling/findpatient', null, 'wheelchair', null, false, 12),
    new Menu(14, 'Register Patient', '/pages/scheduling/registerpatient', null, 'file-text', null, false, 12),
    new Menu(15, 'Check Availability', '/pages/scheduling/chkavl', null, 'file-text-o', null, false, 12),
    new Menu(16, 'Forms', '/pages/scheduling/forms', null, 'file', null, false, 12),
    new Menu(17, 'User Schedule', '/pages//scheduling/userschedule', null, 'clock-o', null, false, 12),
    new Menu(18, 'View All Appointments', '/pages/scheduling/v-all-appointments', null, 'stethoscope', null, false, 12),
    new Menu(19, 'View Charts', '/pages/chart', null, 'file-text-o', null, false, 12),
    new Menu(20, 'Reffering Physician', '/pages/scheduling/referringphysician', null, 'user-md', null, false, 12),
    // new Menu(21, 'Register Patients' , '/pages/scheduling/register-patient', null, 'file-text', null, false, 12),
    /*Charts*/
    new Menu(24, 'Charts', '/pages/chart', null, 'area-chart', null, true, 0),
    new Menu(25, 'Patient Details', null, null, 'file-text-o', null, true, 24),
    // new Menu(26, 'Find Patient', '/pages/chart/findpatient', null, 'search', null, false, 25),
    new Menu(27, 'Edit Patient Details', '/pages/chart/edt-pt-details', null, 'pencil', null, false, 25),
    new Menu(28, 'Progress Note', '/pages/chart/progressnote', null, 'sticky-note', null, false, 25),
    new Menu(29, 'Prescribe', '/prescribe/1', null, 'adjust', '_blank', false, 25),
    // new Menu(30, 'Add Details', null, null, 'plus-square', null, true, 24),
    new Menu(31, 'Add Problem', '/pages/chart/add-problems', null, 'plus-square', null, false, 30),
    new Menu(32, 'Add PMH', '/pages/chart/add-pmh', null, 'plus-circle', null, false, 30),
    new Menu(33, 'Add Allergy', '/pages/chart/add-allergy', null, 'plus', null, false, 30),
    new Menu(34, 'Immunization Schedule', '/pages/chart/immunz-sche', null, 'file-text-o', null, false, 30),
    new Menu(35, 'Add Vitals', '/pages/chart/add-vitals', null, 'area-chart', null, false, 30),
    new Menu(36, 'Add Investigation', '/pages/chart/add-invest', null, 'area-chart', null, false, 30),
    new Menu(37, 'Graphs', '/pages/chart/graphs', null, 'area-chart', null, false, 24),
    // new Menu(38, 'Share', null, null, 'share-alt', null, true, 24),
    new Menu(39, 'Documents', '/pages/chart/documents', null, 'file-text-o', null, false, 38),
    new Menu(40, 'Letters', '/pages/chart/letters', null, 'font', null, false, 38),
    new Menu(41, 'Messages', '/pages/chart/msg', null, 'wechat', null, false, 38),
    new Menu(42, 'Sketch Pad', '/pages/chart/sktch-pad', null, 'file', null, false, 38),
    new Menu(43, 'All Charts Print', '/pages/chart/all-chart-pt', null, 'area-chart', null, false, 38),
    /*Billing*/
    new Menu (45, 'Billing', 'pages/billing', null, 'dollar', null, true, 0),
    new Menu (46, 'View Bills', '/pages/billing/viewbills', null, 'cc-visa', null, false, 45),
    new Menu (47, 'Post Charges', '/pages/billing/postcharges', null, 'money', null, false, 45),
    new Menu (48, 'Claims', '/pages/billing/claims', null, 'shopping-bag', null, false, 45),
    new Menu (49, 'Payments', '/pages/billing/payments', null, 'cc-mastercard', null, false, 45),
    new Menu (50, 'Patient Accounts', '/pages/billing/patientaccount', null, 'file-picture-o', null, false, 45),
    new Menu (51, 'Account Receivable', '/pages/billing/accountreceivable', null, 'dollar', null, false, 45),
    new Menu (52, 'Billing Setup', '/pages/billing/billingsetup', null, 'area-chart', null, false, 45),
    new Menu(53, 'Billing Portal', '/pages/billing/billingportal', null, 'pie-chart', null, false, 45),
    /*Orders*/
    new Menu(60, 'Orders', "pages/orders", null, 'calendar', null, true, 0),
    new Menu(61, 'Find Patients', '/pages/orders/findpatients', null, 'search', null, false, 60),
    new Menu(62, 'Home', '/pages/orders/home', null, 'home', null, false, 60),
    new Menu(63, 'New Order', '/pages/orders/neworder', null, 'file-text-o', null, false, 60),
    new Menu(64, 'Search', '/pages/orders/search', null, 'search', null, false, 60),
    new Menu(65, 'Inbox', '/pages/orders/inbox', null, 'envelope-o', null, false, 60),
    new Menu(66, 'Admin', null, null, 'calendar', null, true, 60),
    new Menu(661, 'Test Code Preference', '/pages/orders/testcodepreference', null, 'file', null, false, 66),
    new Menu(662, 'ICD Code Preference', '/pages/orders/icdcodepreference', null, 'file-text-o', null, false, 66),
    new Menu(67, 'Mail Portal', '/pages/orders/mainportal', null, 'envelope-o', null, false, 60),
    new Menu(68, 'Show Results', '/pages/orders/showresults', null, 'file', null, false, 60),

    /*Practice*/
    new Menu(71, 'Practice', null, null, 'stethoscope', null, true, 0),
    new Menu(72, 'Practive-Mngt', null, null, 'users', null, true, 71),
    new Menu(73, 'Facility', '/pages/practice/facility', null, 'medkit', null, false, 72),
    new Menu(74, 'Practice', '/pages/practice/pm-practice', null, 'user-md', null, false, 72),
    new Menu(75, 'Speciality', '/pages/practice/pm-speciality', null, 'hospital-o', null, false, 72),
    new Menu(76, 'Qualification', '/pages/practice/pm-qual', null, 'stethoscope', null, false, 72),
    new Menu(77, 'Employee Role', '/pages/practice/pm-emp-role', null, 'user', null, false, 72),
    new Menu(78, 'LookUp Table', '/pages/practice/pm-lup-tb', null, 'file-text', null, false, 72),
    new Menu(79, 'Eligibility Verification', '/pages/practice/pm-el-verf', null, 'file', null, false, 72),
    new Menu(80, 'Employee Maintenance', '/pages/practice/pm-employee-maintenance', null, 'usd', null, false, 72),
    new Menu(81, 'Clinical Decition Support', '/pages/practice/pm-cds', null, 'plus-square', null, false, 72),

    new Menu(82, 'Reports', null, null, 'file-text', null, true, 71),
    new Menu(83, 'Patients List', '/pages/practice/rt-pt-list', null, 'file', null, false, 82),
    new Menu(84, 'Audit Report', '/pages/practice/rt-audit-report', null, 'file-text-o', null, false, 82),
    new Menu(85, 'Patient Remainder', '/pages/practice/rt-pt-remainder', null, 'weixin', null, false, 82),
    new Menu(86, 'Stage1 MU Measures', '/pages/practice/rt-mum', null, 'calendar', null, false, 82),
    new Menu(87, 'Clinical Qty Measure', '/pages/practice/rt-cqm', null, 'hospital-o', null, false, 82),

    new Menu(88, 'Health Info Exg', null, null, 'plus-square', null, true, 71),
    new Menu(89, 'Ept/Dpt EHI', '/pages/practice/hie-ed-ehi', null, null, null, false, 88),
    new Menu(90, 'Generate SHA256', '/pages/practice/hie-audit-gshah', null, null, null, false, 88),
    new Menu(91, 'General Enc Test', '/pages/practice/hie-getst', null, null, null, false, 88),
    new Menu(92, 'Public Health Surv', '/pages/practice/hie-phs', null, null, null, false, 88),
    new Menu(93, 'Electronic Exg Cpt', '/pages/practice/hie-eec', null, null, null, false, 88),
    new Menu(94, 'Exg Clinical Info', '/pages/practice/hie-exc-cli-info', null, null, null, false, 88),
    new Menu(95, 'Imm.Reg Submission', '/pages/practice/hie-irs', null, null, null, false, 88),
    new Menu(96, 'Sync DrFirst Data', '/pages/practice/hie-sdd', null, null, null, false, 88),


    new Menu(97, 'Administration', null, null, 'user', null, true, 71),
    new Menu(98, 'Modality', '/pages/practice/admin-modality', null, 'file', null, false, 97),
    new Menu(99, 'Department', '/pages/practice/admin-dept', null, 'hospital-o', null, false, 97),
    new Menu(100, 'Place Of Service', '/pages/practice/admin-pos', null, 'map-marker', null, false, 97),
    new Menu(101, 'Calendar Event', '/pages/practice/admin-cal-evt', null, 'calendar', null, false, 97),
    new Menu(102, 'Reffering Physician', '/pages/practice/admin-reff-phy', null, 'user-md', null, false, 97),
    new Menu(103, 'Related Organization', '/pages/practice/admin-rlorg', null, 'ge', null, false, 97),
    new Menu(104, 'Unit of Measure', '/pages/practice/admin-uom', null, 'usd', null, false, 97),
    new Menu(105, 'CPT4 Codes', '/pages/practice/admin-cptcode', null, 'qrcode', null, false, 97),
    new Menu(106, 'Laboratories', '/pages/practice/admin-lab', null, 'ambulance', null, false, 97),
    new Menu(107, 'Lab Investigations', '/pages/practice/admin-lab-invest', null, 'file-text', null, false, 97),
    new Menu(108, 'Investigations', '/pages/practice/admin-invest', null, 'file', null, false, 97),
    new Menu(109, 'Merge Patient', '/pages/practice/admin-mg-patient', null, 'wheelchair', null, false, 97),

    new Menu(110, 'Template', null, null, null, null, true, 88),
    new Menu(111, 'Section Builder', '/pages/practice/templat-sb', null, 'caret-right', null, false, 110),
    new Menu(112, 'Smart Text Lookups', '/pages/practice/template-stl', null, 'caret-right', null, false, 110),
    new Menu(113, 'Smart Note Template', '/pages/practice/template-snt', null, 'caret-right', null, false, 110),
    new Menu(114, 'Template Group', '/pages/practice/template-tg', null, 'caret-right', null, false, 110),
    new Menu(115, 'Patient Edu Resource', '/pages/practice/template-per', null, 'caret-right', null, false, 110),
    new Menu(116, 'Letter Template', '/pages/practice/template-lt', null, 'caret-right', null, false, 110),
    new Menu(117, 'Encounter Sum Temp', '/pages/practice/template-est', null, 'caret-right', null, false, 110),

    /*Reports*/
    new Menu(121, 'Reports', '/pages/reports/reports', null, 'file-text', null, true, 0),
    new Menu(123, 'Appointments', '/pages/reports/appointments', null, 'file', null, false, 121),
    new Menu(124, 'Billing', '/pages/reports/billing', null, 'usd', null, false, 121),
    new Menu(125, 'Patients', '/pages/reports/patients', null, 'user-o', null, false, 121),
    new Menu(126, 'Practice', '/pages/reports/practice', null, 'user-md', null, false, 121),
    new Menu(127, 'Users', '/pages/reports/userst', null, 'users', null, false, 121),
     /*Scanning*/
    new Menu(131, 'Scanning', '/pages/scanning', null, 'search', null, true, 0),
    new Menu(132, 'Find Patients', '/pages/scanning/findpatients', null, 'search', null, false, 131),
    new Menu(133, 'Documents', '/pages/scanning/documents', null, 'file-text', null, false, 131),

    /*Inventory*/
    new Menu(136, 'Inventory', '/pages/inventory/tracking', null,  'list', null, true, 0),
    new Menu(137, 'Tracking', '/pages/inventory/tracking', null, 'map-marker', null, false, 136),
    new Menu(138, 'Items', '/pages/inventory/items', null, 'list', null, false, 136),
    new Menu(139, 'Batches', '/pages/inventory/batches', null, 'object-group', null, false, 136),
    new Menu(140, 'Orders', '/pages/inventory/orderMaster', null, 'shopping-cart', null, false, 136),
    new Menu(141, 'Shipping', '/pages/inventory/shipping', null, 'truck', null, false, 136),
    new Menu(142, 'Categories', '/pages/inventory/categories', null, 'tags', null, false, 136),
    new Menu(143, 'Upload', '/pages/inventory/uploads', null, 'upload', null, false, 136),

    /* Profile */
    new Menu(144, 'Profile', '/pages/profile', null, 'user', null, false, 0),

    /*Help*/
    new Menu(145, 'Help', '/pages/help/videos', null, 'question', null, true, 0),
    new Menu(146, 'Videos', '/pages/help/videos', null, 'youtube-play', null, false, 145),
    new Menu(147, 'User Manual', '/pages/help/um', null, 'file', null, false, 145),
    new Menu(148, 'Whats New', '/pages/help/whatsnew', null, 'question', null, false, 145),
    new Menu(149, 'About', '/pages/help/about', null, 'user-o', null, false, 145),
    /*Logout*/
    // new Menu(151, 'Log Out', null, null, 'calendar', null, false, 0),

    /*new Menu (1, 'Dashboard', '/pages/dashboard', null, 'tachometer', null, false, 0),
    new Menu (2, 'Membership', '/pages/membership', null, 'users', null, false, 0),
    new Menu (3, 'UI Features', null, null, 'laptop', null, true, 0),
    new Menu (4, 'Buttons', '/pages/ui/buttons', null, 'keyboard-o', null, false, 3),
    new Menu (5, 'Cards', '/pages/ui/cards', null, 'address-card-o', null, false, 3),
    new Menu (6, 'Components', '/pages/ui/components', null, 'creative-commons', null, false, 3),
    new Menu (7, 'Icons', '/pages/ui/icons', null, 'font-awesome', null, false, 3),
    new Menu (8, 'List Group', '/pages/ui/list-group', null, 'th-list', null, false, 3),
    new Menu (9, 'Media Objects', '/pages/ui/media-objects', null, 'object-group', null, false, 3),
    new Menu (10, 'Tabs & Accordions', '/pages/ui/tabs-accordions', null, 'server', null, false, 3),
    new Menu (11, 'Typography', '/pages/ui/typography', null, 'font', null, false, 3),
    new Menu (31, 'Tools', null, null, 'wrench', null, true, 3),
    new Menu (32, 'Drag & Drop', '/pages/tools/drag-drop', null, 'hand-paper-o', null, false, 31),
    new Menu (33, 'Resizable', '/pages/tools/resizable', null, 'expand', null, false, 31),
    new Menu (34, 'Toaster', '/pages/tools/toaster', null, 'bell-o', null, false, 31),
    new Menu (20, 'Form Elements', null, null, 'pencil-square-o', null, true, 0),
    new Menu (21, 'Form Controls', '/pages/form-elements/controls', null, 'check-square-o', null, false, 20),
    new Menu (22, 'Form Layouts', '/pages/form-elements/layouts', null, 'th-large', null, false, 20),
    new Menu (23, 'Form Validations', '/pages/form-elements/validations', null, 'exclamation-triangle', null, false, 20),
    new Menu (24, 'Form Wizard', '/pages/form-elements/wizard', null, 'magic', null, false, 20),
    new Menu (25, 'Editor', '/pages/form-elements/editor', null, 'pencil', null, false, 20),
    new Menu (26, 'Tables', null, null, 'table', null, true, 20),
    new Menu (27, 'Basic Tables', '/pages/tables/basic-tables', null, 'th', null, false, 26),
    new Menu (28, 'Dynamic Tables', null, null, 'th-large', null, true, 26),
    new Menu (29, 'Smart DataTable', '/pages/tables/dynamic-tables/smart', null, 'caret-right', null, false, 28),
    new Menu (30, 'NGX DataTable', '/pages/tables/dynamic-tables/ngx', null, 'caret-right', null, false, 28),
    new Menu (40, 'Pages', null, null, 'file-text-o', null, true, 0),
    new Menu (15, 'Dynamic Menu', '/pages/dynamic-menu', null, 'list-ul', null, false, 40),
    new Menu (43, 'Login', '/login', null, 'sign-in', null, false, 40),
    new Menu (44, 'Register', '/register', null, 'registered', null, false, 40),
    new Menu (45, 'Blank', '/pages/blank', null, 'file-o', null, false, 40),
    new Menu (46, 'Error', '/pagenotfound', null, 'exclamation-circle', null, false, 40),
    new Menu (50, 'Calendar', '/pages/calendar', null, 'calendar', null, false, 40),
    new Menu (16, 'Mailbox', '/pages/mailbox', null, 'envelope-o', null, false, 40),
    new Menu (200, 'External Link', null, 'http://themeseason.com', 'external-link', '_blank', false, 40),
    new Menu (66, 'Maps', null, null, 'globe', null, true, 0),
    new Menu (67, 'Google Maps', '/pages/maps/googlemaps', null, 'map-marker', null, false, 66),
    new Menu (68, 'Leaflet Maps', '/pages/maps/leafletmaps', null, 'map-o', null, false, 66),
    new Menu (70, 'Charts', null, null, 'area-chart', null, true, 0),
    new Menu (71, 'Bar Charts', '/pages/charts/bar', null, 'bar-chart', null, false, 70),
    new Menu (72, 'Pie Charts', '/pages/charts/pie', null, 'pie-chart', null, false, 70),
    new Menu (73, 'Line Charts', '/pages/charts/line', null, 'line-chart', null, false, 70),
    new Menu (74, 'Bubble Charts', '/pages/charts/bubble', null, 'comment-o', null, false, 70)
    */
]
